# Generated by Django 4.2.4 on 2024-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
    ]
