# Generated by Django 4.2.4 on 2024-10-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0002_centersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload the client logo image', upload_to='client_logos/')),
                ('alt_text', models.CharField(help_text='Alt text for the image', max_length=100)),
            ],
        ),
    ]
