# Generated by Django 4.2.4 on 2024-10-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0003_clientlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlogo',
            old_name='logo',
            new_name='image',
        ),
    ]
