# Generated by Django 4.2.4 on 2024-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0004_rename_logo_clientlogo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title (e.g., 'Our Mission', 'Our Vision')", max_length=100)),
                ('description', models.TextField(help_text='Description for the mission or vision')),
                ('link_url', models.URLField(blank=True, help_text='Optional link for the arrow link', null=True)),
            ],
        ),
    ]
