# Generated by Django 4.2.4 on 2024-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0006_webdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the FAQ question', max_length=255)),
                ('answer', models.TextField(help_text='Enter the FAQ answer')),
            ],
        ),
    ]
