# Generated by Django 4.2.4 on 2024-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus_intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the image for the section', upload_to='digital_transformation/')),
                ('heading', models.CharField(help_text='Enter the main heading', max_length=200)),
                ('paragraph', models.TextField(help_text='Enter the main paragraph')),
                ('highlight_text', models.CharField(help_text='Highlight text for emphasis', max_length=100)),
            ],
        ),
    ]
