# Generated by Django 4.2.4 on 2024-10-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0008_aboutus_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the question text', max_length=255)),
                ('content', models.TextField(help_text='Enter the testimonial content')),
            ],
        ),
    ]
