# Generated by Django 4.2.4 on 2024-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0012_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter the blog slug', max_length=200, unique=True),
        ),
    ]
