# Generated by Django 5.0.4 on 2024-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0013_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, help_text='Link to redirect when clicked', max_length=500),
        ),
    ]
