# Generated by Django 5.0.4 on 2024-11-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0014_portfolio_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='button_text',
        ),
    ]
