# Generated by Django 5.0.4 on 2024-11-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softverses_webapp', '0015_remove_portfolio_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
    ]
