from django.urls import path
from  softverses_webapp import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('web_development/', views.web_development, name='web_development'),
    path('digital_marketing/', views.digital_marketing, name='digital_marketing'),
    path('branding/', views.branding, name='branding'),
    path('blog_details/<int:blog_id>/<slug:slug>/', views.blog_details, name='blog_details'),
    path('blog_page/', views.blog_page, name='blog_page'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('contact_messages',views.contact_messages, name='contact_messages'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('delete_contact_message/<int:delet_type>/',views.delete_contact_message,name='delete_contact_message'),
    path('add_center/', views.add_center, name='add_center'),
    path('edit_center/<int:content_id>/', views.edit_center, name='edit_center'),
    path('delete_center/<int:opening_id>/', views.delete_center, name='delete_center'),
    path('add_logo/', views.add_logo, name='add_logo'),
    path('edit_logo/<int:service_id>/', views.edit_logo, name='edit_logo'),
    path('delete_logo/<int:opening_id>/', views.delete_logo, name='delete_logo'),
    path('add_mission/', views.add_mission, name='add_mission'),
    path('edit_mission/<int:content_id>/', views.edit_mission, name='edit_mission'),
    path('delete_mission/<int:opening_id>/', views.delete_mission, name='delete_mission'),
    path('add_design/', views.add_design, name='add_design'),
    path('edit_design/<int:service_id>/', views.edit_design, name='edit_design'),
    path('delete_design/<int:opening_id>/', views.delete_design, name='delete_design'),
    path('add_faq/', views.add_faq, name='add_faq'),
    path('edit_faq/<int:content_id>/', views.edit_faq, name='edit_faq'),
    path('delete_faq/<int:opening_id>/', views.delete_faq, name='delete_faq'),
    path('add_about/', views.add_about, name='add_about'),
    path('edit_about/<int:content_id>/', views.edit_about, name='edit_about'),
    path('delete_about/<int:opening_id>/', views.delete_about, name='delete_about'),
    path('add_slider/', views.add_slider, name='add_slider'),
    path('edit_slider/<int:service_id>/', views.edit_slider, name='edit_slider'),
    path('delete_slider/<int:opening_id>/', views.delete_slider, name='delete_slider'),
    path('add_why/', views.add_why, name='add_why'),
    path('edit_why/<int:content_id>/', views.edit_why, name='edit_why'),
    path('delete_why/<int:opening_id>/', views.delete_why, name='delete_why'),
    path('add_portfolio/', views.add_portfolio, name='add_portfolio'),
    path('edit_portfolio/<int:content_id>/', views.edit_portfolio, name='edit_portfolio'),
    path('delete_portfolio/<int:opening_id>/', views.delete_portfolio, name='delete_portfolio'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('edit_blog/<int:service_id>/', views.edit_blog, name='edit_blog'),
    path('delete_blog/<int:opening_id>/', views.delete_blog, name='delete_blog'),
    path('thank_you',views.thank_you,name='thank_you'),
    path('terms_and_conditions',views.terms_and_conditions,name='terms_and_conditions'),
    
]
